[general]
import = [
    "~/.config/alacritty/themes/solarized_mod.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[mouse]
bindings = [
    { mouse = "WheelUp", mods = "Alt", action = "ScrollHalfPageUp" },
    { mouse = "WheelDown", mods = "Alt", action = "ScrollHalfPageDown" },
]

[bell]
animation = "Linear"
duration = 250
